### ISSUE TITLE
MemoryError when calculate IS

### ISSUE THREAD

**Issue by limbo0000** [ajbrock/BigGAN-PyTorch#13]
I want to train the BigGAN on Places365 dataset and rewrite the dataloader. It is ok to make hdf5 file. However, when I run the calculate_inception_moments.py, It encounters the memory error. The log is below:
‘’‘
Traceback (most recent call last):
  File "calculate_inception_moments.py", line 93, in <module>
    main()
  File "calculate_inception_moments.py", line 89, in main
    run(config)
  File "calculate_inception_moments.py", line 68, in run
    pool, logits, labels = [np.concatenate(item, 0) for item in [pool, logits, labels]]
  File "calculate_inception_moments.py", line 68, in <listcomp>
    pool, logits, labels = [np.concatenate(item, 0) for item in [pool, logits, labels]]
MemoryError
’‘’
Do you know how to solve the problem?  Looking forward to your reply.
Thanks

**Comment by ajbrock** [comment]
Hi Ceyuan,

This is an out-of-memory error due to a lack of RAM. This presumably happens because the `calculate_inception_moments` script stores all of the accumulated pool/logits values in memory. You can get around this by having more RAM, by not using `--load_in_mem` (which loads the entire dataset hdf5 into memory), or by modifying the script to save the pool, logits, & labels to disk at each iteration instead of keeping them in RAM.
